
CREATE TABLE PRODUTO (
 COD_PRODUTO char(4) NOT NULL,
 DES_PRODUTO varchar(30),
 STA_STATUS char(1),
 PRIMARY KEY (COD_PRODUTO)
)

CREATE TABLE PRODUTO_COSIF (
 COD_PRODUTO char(4) NOT NULL,
 COD_COSIF char(11) NOT NULL,
 COD_CLASSIFICACAO char(6),
 STA_STATUS char(1),
 PRIMARY KEY (COD_COSIF, COD_PRODUTO)
)

ALTER TABLE PRODUTO_COSIF
ADD CONSTRAINT FK_PRODUTO
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)

CREATE TABLE MOVIMENTO_MANUAL (
 DAT_MES numeric(2, 0) NOT NULL,
 DAT_ANO numeric(4, 0) NOT NULL,
 NUM_LANCAMENTO numeric(18, 0) NOT NULL,
 COD_PRODUTO char(4) NOT NULL,
 COD_COSIF char(11) NOT NULL,
 DES_DESCRICAO varchar(50) NOT NULL,
 DAT_MOVIMENTO smalldatetime NOT NULL,
 COD_USUARIO varchar(15) NOT NULL,
 VAL_VALOR numeric(18, 2) NOT NULL,
 PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF)
)

ALTER TABLE MOVIMENTO_MANUAL
ADD CONSTRAINT FK_MOVIMENTO_COSIF
FOREIGN KEY (COD_COSIF, COD_PRODUTO) REFERENCES PRODUTO_COSIF(COD_COSIF, COD_PRODUTO)


